// This file is auto-generated by a script (See web repo ./scripts/*). Do not edit directly.

using System;
using System.Collections.Generic;

namespace HKViz.Silk.GameData;

public static class SilkSongSceneDataGeoRockIds {
    public static readonly Dictionary<string, ushort> VALUE_TO_ID = new(StringComparer.OrdinalIgnoreCase) {
        ["Geo Rock 3"] = 1,
        ["Geo Rock 1 (1)"] = 2,
        ["Geo Rock 2"] = 3,
        ["Geo Rock 1"] = 4,
        ["Geo Rock 2 (1)"] = 5,
        ["Geo Rock Deepnest"] = 6,
        ["Geo Rock Deepnest (1)"] = 7,
    };
}
