// This file is auto-generated by a script (See web repo ./scripts/*). Do not edit directly.

using System;
using System.Collections.Generic;

namespace HKViz.Silk.GameData;

public static class SilkSongToolLiquidIds {
    public static readonly Dictionary<string, ushort> VALUE_TO_ID = new(StringComparer.OrdinalIgnoreCase) {
        ["Flea Brew"] = 1,
        ["Lifeblood Syringe"] = 2,
    };
}
