// This file is auto-generated by a script (See web repo ./scripts/*). Do not edit directly.

using System;
using System.Collections.Generic;

namespace HKViz.Silk.GameData;

public static class SilkSongToolCrestIds {
    public static readonly Dictionary<string, ushort> VALUE_TO_ID = new(StringComparer.OrdinalIgnoreCase) {
        ["Hunter"] = 1,
        ["Hunter_v2"] = 2,
        ["Hunter_v3"] = 3,
        ["Reaper"] = 4,
        ["Wanderer"] = 5,
        ["Warrior"] = 6,
        ["Witch"] = 7,
        ["Toolmaster"] = 8,
        ["Spell"] = 9,
        ["Cursed"] = 10,
        ["Cloakless"] = 11,
    };
}
