// This file is auto-generated by a script (See web repo ./scripts/*). Do not edit directly.

using System;
using System.Collections.Generic;

namespace HKViz.Silk.GameData;

public static class SilkSongExtraToolSlotIds {
    public static readonly Dictionary<string, ushort> VALUE_TO_ID = new(StringComparer.OrdinalIgnoreCase) {
        ["Defend1"] = 1,
        ["Explore1"] = 2,
    };
}
